services:
  go:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ./backend:/app
    networks:
      - backend-network

  peerjs:
    image: peerjs/peerjs-server
    platform: linux/amd64
    ports:
      - ${PEERJS_PORT}:${PEERJS_PORT}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge